import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';
import jsPDF from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const { simulationId } = await req.json();

    if (!simulationId) {
      return Response.json({ error: 'simulationId required' }, { status: 400 });
    }

    const simulation = await base44.entities.FinishingSimulation.filter({ id: simulationId }).then(s => s[0]);
    if (!simulation) {
      return Response.json({ error: 'Simulation not found' }, { status: 404 });
    }

    const property = await base44.entities.Property.filter({ id: simulation.propertyId }).then(p => p[0]);
    const currency = simulation.currencyId || 'EGP';

    // Create PDF
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 20;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(124, 58, 237); // Purple
    doc.text('✨ FINISHING ESTIMATE REPORT', pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Property Info
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Property: ${property?.title || 'Unknown'}`, 20, yPos);
    yPos += 8;
    doc.text(`Area: ${property?.area_size || '—'} sqm | Beds: ${property?.beds || '—'} | Baths: ${property?.baths || '—'}`, 20, yPos);
    yPos += 12;

    // Selections
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`Current State: ${simulation.currentState} | Style: ${simulation.desiredStyle} | Tier: ${simulation.desiredTier}`, 20, yPos);
    yPos += 10;

    // Cost Summary
    doc.setFillColor(245, 243, 255); // Light purple
    doc.rect(20, yPos, pageWidth - 40, 30, 'F');
    doc.setFontSize(14);
    doc.setTextColor(124, 58, 237);
    doc.text('ESTIMATED TOTAL COST', 25, yPos + 10);
    doc.setFontSize(20);
    doc.text(`${currency} ${Math.round(simulation.estimatedTotalMin)} — ${Math.round(simulation.estimatedTotalMax)}`, 25, yPos + 22);
    yPos += 40;

    // Timeline
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Timeline: ${simulation.estimatedWeeksMin} — ${simulation.estimatedWeeksMax} weeks`, 20, yPos);
    yPos += 12;

    // Cost Breakdown
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text('COST BREAKDOWN', 20, yPos);
    yPos += 8;
    doc.setFontSize(10);
    doc.text(`Materials: ${currency} ${Math.round(simulation.estimatedMaterialsCost)}`, 20, yPos);
    yPos += 6;
    doc.text(`Labor: ${currency} ${Math.round(simulation.estimatedLaborCost)}`, 20, yPos);
    yPos += 12;

    // BoQ
    if (simulation.aiGeneratedBoQ && Array.isArray(simulation.aiGeneratedBoQ)) {
      doc.setFontSize(12);
      doc.setTextColor(60, 60, 60);
      doc.text('BILL OF QUANTITIES', 20, yPos);
      yPos += 8;
      doc.setFontSize(9);

      for (const item of simulation.aiGeneratedBoQ.slice(0, 6)) {
        if (yPos > pageHeight - 30) {
          doc.addPage();
          yPos = 20;
        }
        doc.setTextColor(100, 100, 100);
        doc.text(`${item.category}`, 20, yPos);
        doc.text(`Mat: ${currency}${Math.round(item.materialCost)} | Lab: ${currency}${Math.round(item.laborCost)}`, 120, yPos);
        yPos += 6;
      }
    }

    // Design Advice
    yPos += 8;
    if (simulation.aiDesignAdvice) {
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.text('DESIGN RECOMMENDATIONS', 20, yPos);
      yPos += 6;
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      const lines = doc.splitTextToSize(simulation.aiDesignAdvice, pageWidth - 40);
      doc.text(lines, 20, yPos);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Kemedar AI Buy-It-Finished Simulator', pageWidth / 2, pageHeight - 10, { align: 'center' });

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="finishing-estimate.pdf"'
      }
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});