"use client";
import { useState } from "react";
import { useSnapAndFix } from "@/hooks/use-kemework";
import { Camera, Upload, Loader2, AlertTriangle, Wrench } from "lucide-react";
export default function SnapFixPage() {
  const [imageUrl, setImageUrl] = useState(""); const snapMutation = useSnapAndFix();
  const handleAnalyze = () => { if (imageUrl) snapMutation.mutate({ imageUrl }); };
  return (<div className="container mx-auto max-w-3xl py-8 px-4">
    <div className="text-center mb-8"><Camera className="w-12 h-12 text-orange-600 mx-auto mb-3"/><h1 className="text-3xl font-bold">Snap & Fix</h1><p className="text-slate-500 mt-2">Take a photo of any home issue — AI will diagnose it and find materials + professionals</p></div>
    <div className="bg-white border rounded-xl p-6 mb-6"><div className="border-2 border-dashed border-slate-300 rounded-xl p-8 text-center hover:border-blue-400 transition cursor-pointer"><Upload className="w-10 h-10 text-slate-400 mx-auto mb-3"/><p className="text-slate-500 mb-2">Drop a photo or click to upload</p><input type="text" value={imageUrl} onChange={e=>setImageUrl(e.target.value)} placeholder="Or paste image URL..." className="w-full px-4 py-2 border rounded-lg text-sm mt-2"/></div><button onClick={handleAnalyze} disabled={!imageUrl||snapMutation.isPending} className="w-full bg-orange-600 text-white py-3 rounded-lg font-medium mt-4 flex items-center justify-center gap-2 hover:bg-orange-700 disabled:opacity-50">{snapMutation.isPending?<><Loader2 className="w-4 h-4 animate-spin"/>Analyzing...</>:<><Camera className="w-4 h-4"/>Analyze Issue</>}</button></div>
    {snapMutation.data && (<div className="bg-white border rounded-xl p-6"><h3 className="font-bold mb-3 flex items-center gap-2"><Wrench className="w-5 h-5"/>Diagnosis</h3><div className="space-y-2"><div className="flex justify-between"><span className="text-slate-500">Issue Type:</span><span className="font-medium">{(snapMutation.data as any).diagnosis?.issueType}</span></div><div className="flex justify-between"><span className="text-slate-500">Severity:</span><span className="font-medium">{(snapMutation.data as any).diagnosis?.severity}</span></div><div className="flex justify-between"><span className="text-slate-500">Est. Labor Cost:</span><span className="font-medium">{(snapMutation.data as any).diagnosis?.estimatedLaborCostEGP} EGP</span></div></div>{(snapMutation.data as any).diagnosis?.safetyAlerts?.length>0&&<div className="mt-3 bg-red-50 border border-red-200 rounded-lg p-3"><div className="flex items-center gap-1 text-red-700 text-sm font-medium"><AlertTriangle className="w-4 h-4"/>Safety Alerts</div>{(snapMutation.data as any).diagnosis.safetyAlerts.map((a:string,i:number)=><div key={i} className="text-sm text-red-600 mt-1">• {a}</div>)}</div>}</div>)}
  </div>);
}
