"use client";
import Link from "next/link";
import { Hammer, Camera, Search, Shield, Star, Users, Wrench, Paintbrush, Zap, Droplets } from "lucide-react";
const SERVICES = [{name:"Plumber",icon:Droplets,color:"bg-blue-50 text-blue-600"},{name:"Electrician",icon:Zap,color:"bg-amber-50 text-amber-600"},{name:"Painter",icon:Paintbrush,color:"bg-purple-50 text-purple-600"},{name:"Carpenter",icon:Hammer,color:"bg-orange-50 text-orange-600"},{name:"AC Repair",icon:Wrench,color:"bg-cyan-50 text-cyan-600"},{name:"General",icon:Star,color:"bg-green-50 text-green-600"}];
export default function KemeworkHomePage() {
  return (<div>
    <section className="bg-gradient-to-br from-orange-500 to-red-600 text-white py-16 px-4"><div className="container mx-auto max-w-6xl text-center"><h1 className="text-4xl md:text-5xl font-bold mb-4">Home Services Marketplace</h1><p className="text-orange-100 text-lg mb-8">Find trusted professionals for any home service</p><div className="flex flex-col sm:flex-row gap-3 justify-center"><Link href="/kemework/professionals" className="bg-white text-orange-600 px-8 py-3 rounded-lg font-semibold hover:bg-orange-50">Find Professional</Link><Link href="/kemework/snap-fix" className="border-2 border-white px-8 py-3 rounded-lg font-semibold hover:bg-white/10 flex items-center gap-2"><Camera className="w-5 h-5"/>Snap & Fix</Link></div></div></section>
    <section className="py-12 px-4"><div className="container mx-auto max-w-6xl"><h2 className="text-2xl font-bold mb-6">Browse Services</h2><div className="grid grid-cols-3 md:grid-cols-6 gap-4">{SERVICES.map(s=>(<Link key={s.name} href={`/kemework/services?type=${s.name.toLowerCase()}`} className={`rounded-xl border p-4 text-center hover:shadow-md transition ${s.color}`}><s.icon className="w-8 h-8 mx-auto mb-2"/><div className="text-sm font-medium">{s.name}</div></Link>))}</div></div></section>
    <section className="py-12 px-4 bg-slate-50"><div className="container mx-auto max-w-6xl"><h2 className="text-2xl font-bold mb-6">How It Works</h2><div className="grid md:grid-cols-3 gap-6">{[{step:"1",title:"Describe Your Need",desc:"Post a task or use Snap & Fix to diagnose issues"},{step:"2",title:"Get Matched",desc:"Receive quotes from verified professionals"},{step:"3",title:"Get It Done",desc:"Choose a pro, track progress, and pay securely"}].map(s=>(<div key={s.step} className="bg-white rounded-xl border p-6 text-center"><div className="w-10 h-10 bg-orange-100 text-orange-600 rounded-full flex items-center justify-center font-bold mx-auto mb-3">{s.step}</div><h3 className="font-bold mb-1">{s.title}</h3><p className="text-sm text-slate-500">{s.desc}</p></div>))}</div></div></section>
  </div>);
}
