import { useState } from "react";
import { Save, CheckCircle, ChevronRight } from "lucide-react";

function Toggle({ label, checked, onChange }) {
  return (
    <div className="flex items-center justify-between py-2">
      <span className="text-sm text-gray-700">{label}</span>
      <button onClick={() => onChange(!checked)}
        className={`relative flex-shrink-0 rounded-full transition-colors`}
        style={{ width: 40, height: 22, backgroundColor: checked ? '#f97316' : '#e5e7eb' }}>
        <span className="absolute top-0.5 left-0.5 w-[18px] h-[18px] bg-white rounded-full shadow transition-transform"
          style={{ transform: checked ? 'translateX(18px)' : 'translateX(0)' }} />
      </button>
    </div>
  );
}

function Section({ title, description, children }) {
  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-100 bg-gray-50/60">
        <h3 className="font-black text-gray-900 text-sm">{title}</h3>
        {description && <p className="text-xs text-gray-500 mt-0.5">{description}</p>}
      </div>
      <div className="p-5 space-y-4">{children}</div>
    </div>
  );
}

export default function PredictSettings() {
  const [saved, setSaved] = useState(false);

  // Section 1
  const [autoGen, setAutoGen] = useState(true);
  const [topFreq, setTopFreq] = useState("daily");
  const [otherFreq, setOtherFreq] = useState("weekly");
  const [onNewSignal, setOnNewSignal] = useState(true);

  // Section 2
  const [displayOn, setDisplayOn] = useState({
    propertyPages: true, projectPages: true, searchResults: true,
    advisorReports: true, publicDashboard: true, homepage: false,
  });
  const [minConf, setMinConf] = useState(60);
  const [minListings, setMinListings] = useState(10);

  // Section 3
  const [dataWindow, setDataWindow] = useState(12);
  const [decayRate, setDecayRate] = useState(10);

  // Section 4
  const [showDisclaimer, setShowDisclaimer] = useState(true);
  const [disclaimer, setDisclaimer] = useState(`Kemedar Predict™ forecasts are generated by AI using historical listing data and market signals. Predictions are not financial advice. Past performance does not guarantee future results. Consult a qualified real estate advisor before making investment decisions.`);
  const [disclaimerAr, setDisclaimerAr] = useState(`توقعات Kemedar Predict™ مولودة بواسطة الذكاء الاصطناعي باستخدام بيانات القوائم التاريخية وإشارات السوق. التوقعات ليست نصيحة مالية. الأداء السابق لا يضمن النتائج المستقبلية. استشر مستشاراً متخصصاً في العقارات قبل اتخاذ قرارات الاستثمار.`);

  const handleSave = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  return (
    <div className="space-y-5 max-w-4xl">
      <div className="flex items-center gap-1.5 text-xs text-gray-400">
        <span>Admin</span><ChevronRight size={11} /><span>Kemedar Predict™</span><ChevronRight size={11} />
        <span className="text-gray-700 font-semibold">Settings</span>
      </div>

      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-black text-gray-900">Predict™ Settings</h1>
          <p className="text-gray-500 text-sm">Configure AI generation, display rules, and disclaimers</p>
        </div>
        <button onClick={handleSave}
          className={`flex items-center gap-2 font-bold px-5 py-2.5 rounded-xl text-sm transition-all ${saved ? 'bg-green-500 text-white' : 'bg-orange-500 hover:bg-orange-600 text-white'}`}>
          {saved ? <><CheckCircle size={14} /> Saved!</> : <><Save size={14} /> Save Settings</>}
        </button>
      </div>

      <Section title="⏱ Generation Schedule" description="How often predictions are auto-generated">
        <Toggle label="Auto-generate predictions" checked={autoGen} onChange={setAutoGen} />
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1">Top areas frequency</label>
            <select value={topFreq} onChange={e => setTopFreq(e.target.value)} disabled={!autoGen}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none disabled:opacity-50">
              <option value="daily">Daily</option>
              <option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1">Other areas frequency</label>
            <select value={otherFreq} onChange={e => setOtherFreq(e.target.value)} disabled={!autoGen}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none disabled:opacity-50">
              <option value="daily">Daily</option>
              <option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option>
            </select>
          </div>
        </div>
        <Toggle label="Regenerate on new signal added" checked={onNewSignal} onChange={setOnNewSignal} />
      </Section>

      <Section title="👁 Display Settings" description="Where predictions appear on the platform">
        {Object.entries(displayOn).map(([k, v]) => (
          <Toggle key={k}
            label={k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())}
            checked={v}
            onChange={val => setDisplayOn(prev => ({...prev, [k]: val}))}
          />
        ))}
        <div className="grid grid-cols-2 gap-4 pt-2 border-t border-gray-100">
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1">Min confidence to display ({minConf}%)</label>
            <input type="range" min="0" max="100" value={minConf} onChange={e => setMinConf(parseInt(e.target.value))}
              className="w-full accent-orange-500" />
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1">Min listings required</label>
            <input type="number" value={minListings} onChange={e => setMinListings(parseInt(e.target.value))} min="1"
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-orange-400" />
          </div>
        </div>
      </Section>

      <Section title="🤖 AI Configuration" description="Model and data parameters">
        <div className="bg-gray-50 rounded-xl p-3 text-xs text-gray-600 space-y-1">
          <p><strong>Model:</strong> claude-sonnet-4-20250514</p>
          <p><strong>Temperature:</strong> 0.3 (conservative)</p>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1">Historical data window (months)</label>
            <input type="number" value={dataWindow} onChange={e => setDataWindow(parseInt(e.target.value))} min="3" max="36"
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-orange-400" />
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1">Signal decay rate (% per month)</label>
            <input type="number" value={decayRate} onChange={e => setDecayRate(parseInt(e.target.value))} min="0" max="50"
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-orange-400" />
          </div>
        </div>
      </Section>

      <Section title="⚖️ Disclaimer Settings" description="Legal disclaimer shown on all predictions">
        <Toggle label="Show disclaimer on all predictions (recommended)" checked={showDisclaimer} onChange={setShowDisclaimer} />
        <div>
          <label className="block text-xs font-bold text-gray-500 mb-1">Disclaimer text (English)</label>
          <textarea value={disclaimer} onChange={e => setDisclaimer(e.target.value)} rows={4}
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-orange-400 resize-none" />
        </div>
        <div>
          <label className="block text-xs font-bold text-gray-500 mb-1">Disclaimer text (Arabic)</label>
          <textarea value={disclaimerAr} onChange={e => setDisclaimerAr(e.target.value)} rows={4} dir="rtl"
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-orange-400 resize-none" />
        </div>
      </Section>

      <div className="flex justify-end">
        <button onClick={handleSave}
          className={`flex items-center gap-2 font-bold px-6 py-3 rounded-xl text-sm transition-all ${saved ? 'bg-green-500 text-white' : 'bg-orange-500 hover:bg-orange-600 text-white'}`}>
          {saved ? <><CheckCircle size={14} /> Saved!</> : <><Save size={14} /> Save All Settings</>}
        </button>
      </div>
    </div>
  );
}