// ─── SEED DATA FOR RBAC SYSTEM ───────────────────────────────────────────────

export const SYSTEM_ROLES = [
  { roleKey: "guest", displayName: "Non-Logged-In User", displayNameAr: "زائر", module: "shared", color: "#9CA3AF", icon: "👤", description: "Non-authenticated visitor. Can preview content with restrictions.", isSystem: true, isActive: true, sortOrder: 1 },
  { roleKey: "common_user", displayName: "Common User", displayNameAr: "مستخدم عادي", module: "kemedar", color: "#6B7280", icon: "👤", description: "Registered user with basic access to browse and post listings.", isSystem: true, isActive: true, sortOrder: 2, parentRoleKey: "guest" },
  { roleKey: "agent", displayName: "Real Estate Agent", displayNameAr: "وكيل عقاري", module: "kemedar", color: "#3B82F6", icon: "🤝", description: "Licensed agent who can list properties and manage clients.", isSystem: true, isActive: true, sortOrder: 3, parentRoleKey: "common_user" },
  { roleKey: "agency", displayName: "Real Estate Agency", displayNameAr: "شركة عقارية", module: "kemedar", color: "#8B5CF6", icon: "🏢", description: "Agency that manages multiple agents and properties.", isSystem: true, isActive: true, sortOrder: 4, parentRoleKey: "agent" },
  { roleKey: "developer", displayName: "Real Estate Developer", displayNameAr: "مطور عقاري", module: "kemedar", color: "#1F2937", icon: "🏗", description: "Developer with access to full project and unit management.", isSystem: true, isActive: true, sortOrder: 5, parentRoleKey: "agent" },
  { roleKey: "franchise_owner_area", displayName: "Franchise Owner (Area)", displayNameAr: "مالك فرانشايز (منطقة)", module: "kemedar", color: "#FF6B00", icon: "🗺", description: "Franchise owner managing a specific geographic area.", isSystem: true, isActive: true, sortOrder: 6, parentRoleKey: "agent" },
  { roleKey: "franchise_owner_country", displayName: "Franchise Owner (Country)", displayNameAr: "مالك فرانشايز (دولة)", module: "kemedar", color: "#D4A017", icon: "🌍", description: "Franchise owner with country-level access and management.", isSystem: true, isActive: true, sortOrder: 7, parentRoleKey: "franchise_owner_area" },
  { roleKey: "professional", displayName: "Professional/Handyman", displayNameAr: "حرفي/متخصص", module: "kemework", color: "#2D6A4F", icon: "🔧", description: "Service professional who offers and bids on tasks.", isSystem: true, isActive: true, sortOrder: 8, parentRoleKey: "common_user" },
  { roleKey: "customer_kemework", displayName: "Customer (Kemework)", displayNameAr: "عميل كيميورك", module: "kemework", color: "#059669", icon: "👤", description: "Customer who posts tasks and orders services on Kemework.", isSystem: true, isActive: true, sortOrder: 9, parentRoleKey: "common_user" },
  { roleKey: "finishing_company", displayName: "Finishing Company", displayNameAr: "شركة تشطيبات", module: "kemework", color: "#92400E", icon: "🏢", description: "Company offering finishing and renovation services.", isSystem: true, isActive: true, sortOrder: 10, parentRoleKey: "professional" },
  { roleKey: "product_seller", displayName: "Product Seller", displayNameAr: "بائع منتجات", module: "kemetro", color: "#0077B6", icon: "🏪", description: "Seller with a store on Kemetro marketplace.", isSystem: true, isActive: true, sortOrder: 11, parentRoleKey: "common_user" },
  { roleKey: "product_buyer", displayName: "Product Buyer", displayNameAr: "مشتري منتجات", module: "kemetro", color: "#0EA5E9", icon: "🛒", description: "Buyer on the Kemetro marketplace.", isSystem: true, isActive: true, sortOrder: 12, parentRoleKey: "common_user" },
  { roleKey: "shipper", displayName: "Shipper/Courier", displayNameAr: "مندوب شحن", module: "kemetro", color: "#0369A1", icon: "🚚", description: "Shipper who handles deliveries for Kemetro orders.", isSystem: true, isActive: true, sortOrder: 13, parentRoleKey: "common_user" },
  { roleKey: "admin", displayName: "Administrator", displayNameAr: "مشرف", module: "admin", color: "#EF4444", icon: "🔑", description: "Platform administrator with broad management access.", isSystem: true, isActive: true, sortOrder: 14 },
  { roleKey: "super_admin", displayName: "Super Admin", displayNameAr: "مشرف عام", module: "admin", color: "#7C2D12", icon: "👑", description: "Super administrator with unrestricted access to everything.", isSystem: true, isActive: true, sortOrder: 15, parentRoleKey: "admin" },
];

export const PERMISSION_ACTIONS = [
  { actionKey: "view", displayName: "View / Read", description: "Can view and read this resource", category: "read", isDestructive: false, sortOrder: 1 },
  { actionKey: "create", displayName: "Create / Add New", description: "Can create new records", category: "write", isDestructive: false, sortOrder: 2 },
  { actionKey: "edit", displayName: "Edit / Update", description: "Can edit existing records", category: "write", isDestructive: false, sortOrder: 3 },
  { actionKey: "delete", displayName: "Delete / Remove", description: "Can delete records", category: "write", isDestructive: true, sortOrder: 4 },
  { actionKey: "submit", displayName: "Submit / Send", description: "Can submit forms or requests", category: "write", isDestructive: false, sortOrder: 5 },
  { actionKey: "publish", displayName: "Publish / Make Live", description: "Can publish to public", category: "write", isDestructive: false, sortOrder: 6 },
  { actionKey: "approve", displayName: "Approve", description: "Can approve pending items", category: "moderation", isDestructive: false, sortOrder: 7 },
  { actionKey: "reject", displayName: "Reject / Decline", description: "Can reject or decline items", category: "moderation", isDestructive: false, sortOrder: 8 },
  { actionKey: "verify", displayName: "Verify / Certify", description: "Can verify users or listings", category: "moderation", isDestructive: false, sortOrder: 9 },
  { actionKey: "feature", displayName: "Mark as Featured", description: "Can mark items as featured", category: "moderation", isDestructive: false, sortOrder: 10 },
  { actionKey: "export", displayName: "Export Data", description: "Can export data to CSV/Excel", category: "admin", isDestructive: false, sortOrder: 11 },
  { actionKey: "import", displayName: "Import Data", description: "Can import data in bulk", category: "admin", isDestructive: false, sortOrder: 12 },
  { actionKey: "bid", displayName: "Submit Bid / Offer", description: "Can submit bids or offers", category: "write", isDestructive: false, sortOrder: 13 },
  { actionKey: "assign", displayName: "Assign to User/Role", description: "Can assign resources to others", category: "admin", isDestructive: false, sortOrder: 14 },
  { actionKey: "accredit", displayName: "Accredit User", description: "Can grant accreditation status", category: "moderation", isDestructive: false, sortOrder: 15 },
  { actionKey: "message", displayName: "Send Message", description: "Can send messages", category: "communication", isDestructive: false, sortOrder: 16 },
  { actionKey: "purchase", displayName: "Purchase / Order", description: "Can make purchases or orders", category: "financial", isDestructive: false, sortOrder: 17 },
  { actionKey: "refund", displayName: "Request Refund", description: "Can request refunds", category: "financial", isDestructive: false, sortOrder: 18 },
  { actionKey: "withdraw", displayName: "Withdraw Funds", description: "Can withdraw earnings", category: "financial", isDestructive: false, sortOrder: 19 },
  { actionKey: "upload_media", displayName: "Upload Photos/Files", description: "Can upload media files", category: "write", isDestructive: false, sortOrder: 20 },
  { actionKey: "access_dashboard", displayName: "Access Dashboard", description: "Can access dashboard section", category: "read", isDestructive: false, sortOrder: 21 },
  { actionKey: "manage", displayName: "Full Management Access", description: "Full management of this resource", category: "admin", isDestructive: false, sortOrder: 22 },
  { actionKey: "bulk_action", displayName: "Bulk Actions", description: "Can perform bulk operations", category: "admin", isDestructive: true, sortOrder: 23 },
];

export const PERMISSION_RESOURCES = [
  // ─── KEMEDAR: PROPERTIES ───
  { resourceKey: "property_listing", displayName: "Property Listing", module: "kemedar", resourceType: "entity", description: "Core property listing entity", availableActions: ["view","create","edit","delete","publish","approve","reject","verify","feature","upload_media","export","import"], sortOrder: 1 },
  { resourceKey: "property_search", displayName: "Search Properties Page", module: "kemedar", resourceType: "page", route: "/kemedar/search-properties", description: "Public property search page", availableActions: ["view"], sortOrder: 2 },
  { resourceKey: "property_detail_page", displayName: "Property Detail Page", module: "kemedar", resourceType: "page", route: "/kemedar/property/:slug", description: "Individual property detail view", availableActions: ["view","message"], sortOrder: 3 },
  { resourceKey: "add_property_form", displayName: "Add Property Form", module: "kemedar", resourceType: "form", route: "/kemedar/add/property", description: "Form to add a new property listing", availableActions: ["view","create","submit","upload_media"], sortOrder: 4 },
  { resourceKey: "buy_request", displayName: "Buy Request", module: "kemedar", resourceType: "entity", description: "Property buy request entity", availableActions: ["view","create","edit","delete","submit","approve","reject","export"], sortOrder: 5 },
  { resourceKey: "add_buy_request_form", displayName: "Add Buy Request Form", module: "kemedar", resourceType: "form", route: "/kemedar/add/buy-request", description: "Form to post a buy request", availableActions: ["view","create","submit"], sortOrder: 6 },
  { resourceKey: "property_favorites", displayName: "Save to Favorites", module: "kemedar", resourceType: "feature", description: "Save properties to favorites list", availableActions: ["view","create","delete"], sortOrder: 7 },
  { resourceKey: "property_compare", displayName: "Compare Properties", module: "kemedar", resourceType: "feature", description: "Side-by-side property comparison tool", availableActions: ["view"], sortOrder: 8 },
  { resourceKey: "buyer_organizer", displayName: "Buyer Organizer Kanban", module: "kemedar", resourceType: "dashboard_section", description: "Kanban board for buyer pipeline", availableActions: ["view","create","edit","delete"], sortOrder: 9 },
  { resourceKey: "seller_organizer", displayName: "Seller Organizer Kanban", module: "kemedar", resourceType: "dashboard_section", description: "Kanban board for seller pipeline", availableActions: ["view","create","edit","delete"], sortOrder: 10 },
  { resourceKey: "property_valuation_tool", displayName: "Property Valuation Tool", module: "kemedar", resourceType: "feature", description: "AI-powered property valuation wizard", availableActions: ["view","create"], sortOrder: 11 },
  { resourceKey: "property_ai_pricing", displayName: "AI Price Suggestion", module: "kemedar", resourceType: "feature", description: "AI widget that suggests optimal listing price", availableActions: ["view"], sortOrder: 12 },
  { resourceKey: "property_ai_description", displayName: "AI Content Generator (Property)", module: "kemedar", resourceType: "feature", description: "AI-generated titles and descriptions", availableActions: ["view"], sortOrder: 13 },

  // ─── KEMEDAR: PROJECTS ───
  { resourceKey: "project_listing", displayName: "Project Listing", module: "kemedar", resourceType: "entity", description: "Real estate project entity", availableActions: ["view","create","edit","delete","publish","approve","reject","verify","feature","upload_media"], sortOrder: 14 },
  { resourceKey: "project_search", displayName: "Search Projects Page", module: "kemedar", resourceType: "page", route: "/kemedar/search-projects", description: "Public project search page", availableActions: ["view"], sortOrder: 15 },
  { resourceKey: "add_project_form", displayName: "Add Project Form", module: "kemedar", resourceType: "form", route: "/kemedar/add/project", description: "Form to add a new project", availableActions: ["view","create","submit","upload_media"], sortOrder: 16 },
  { resourceKey: "project_units", displayName: "Project Units Management", module: "kemedar", resourceType: "feature", description: "Manage units within a project", availableActions: ["view","create","edit","delete"], sortOrder: 17 },

  // ─── KEMEDAR: USERS/PROFILES ───
  { resourceKey: "agent_profile_page", displayName: "Agent Public Profile", module: "kemedar", resourceType: "page", description: "Public-facing agent profile page", availableActions: ["view","message"], sortOrder: 18 },
  { resourceKey: "find_agents_page", displayName: "Find Agents Page", module: "kemedar", resourceType: "page", description: "Directory of real estate agents", availableActions: ["view"], sortOrder: 19 },
  { resourceKey: "find_agencies_page", displayName: "Find Agencies Page", module: "kemedar", resourceType: "page", description: "Directory of agencies", availableActions: ["view"], sortOrder: 20 },
  { resourceKey: "find_developers_page", displayName: "Find Developers Page", module: "kemedar", resourceType: "page", description: "Directory of developers", availableActions: ["view"], sortOrder: 21 },
  { resourceKey: "find_franchise_page", displayName: "Find Franchise Owners Page", module: "kemedar", resourceType: "page", description: "Directory of franchise owners", availableActions: ["view"], sortOrder: 22 },
  { resourceKey: "agent_dashboard", displayName: "Agent Dashboard", module: "kemedar", resourceType: "dashboard_section", description: "Agent-specific dashboard", availableActions: ["access_dashboard"], sortOrder: 23 },
  { resourceKey: "agent_clients_crm", displayName: "Agent — Clients CRM", module: "kemedar", resourceType: "feature", description: "CRM for managing agent clients", availableActions: ["view","create","edit","delete","export"], sortOrder: 24 },
  { resourceKey: "agent_appointments", displayName: "Agent — Appointments", module: "kemedar", resourceType: "feature", description: "Appointment scheduling for agents", availableActions: ["view","create","edit","delete"], sortOrder: 25 },
  { resourceKey: "agent_analytics", displayName: "Agent — Analytics", module: "kemedar", resourceType: "feature", description: "Performance analytics for agents", availableActions: ["view","export"], sortOrder: 26 },
  { resourceKey: "agency_my_agents", displayName: "Agency — Manage Agents", module: "kemedar", resourceType: "feature", description: "Manage agents under an agency", availableActions: ["view","create","edit","delete","assign"], sortOrder: 27 },
  { resourceKey: "developer_projects", displayName: "Developer — Projects Dashboard", module: "kemedar", resourceType: "feature", description: "Dashboard for developer projects", availableActions: ["view","create","edit","delete"], sortOrder: 28 },
  { resourceKey: "developer_leads", displayName: "Developer — Leads", module: "kemedar", resourceType: "feature", description: "Lead management for developers", availableActions: ["view","create","edit","delete"], sortOrder: 29 },

  // ─── KEMEDAR: FRANCHISE ───
  { resourceKey: "franchise_area_users", displayName: "Franchise — Users in My Area", module: "kemedar", resourceType: "feature", description: "View and manage users in franchise area", availableActions: ["view","verify","message","manage"], sortOrder: 30 },
  { resourceKey: "franchise_area_properties", displayName: "Franchise — Area Properties", module: "kemedar", resourceType: "feature", description: "Manage properties in franchise area", availableActions: ["view","verify","approve","reject","feature"], sortOrder: 31 },
  { resourceKey: "franchise_area_projects", displayName: "Franchise — Area Projects", module: "kemedar", resourceType: "feature", description: "Manage projects in franchise area", availableActions: ["view","verify","approve","reject"], sortOrder: 32 },
  { resourceKey: "franchise_verify_user", displayName: "Franchise — Verify User", module: "kemedar", resourceType: "feature", description: "Verify user identity in area", availableActions: ["verify","reject"], sortOrder: 33 },
  { resourceKey: "franchise_accredit_handyman", displayName: "Franchise — Accredit Handyman", module: "kemedar", resourceType: "feature", description: "Grant accreditation to handymen", availableActions: ["accredit","reject"], sortOrder: 34 },
  { resourceKey: "franchise_kemetro_sellers", displayName: "Franchise — Kemetro Sellers", module: "kemedar", resourceType: "feature", description: "Manage Kemetro sellers in area", availableActions: ["view","verify","reject"], sortOrder: 35 },
  { resourceKey: "franchise_business_manager", displayName: "Franchise — Business Manager", module: "kemedar", resourceType: "feature", description: "Full business management suite for franchisee", availableActions: ["view","create","edit","delete","manage"], sortOrder: 36 },
  { resourceKey: "franchise_bulk_comms", displayName: "Franchise — Bulk Communications", module: "kemedar", resourceType: "feature", description: "Send bulk messages/emails to area users", availableActions: ["view","create","submit"], sortOrder: 37 },

  // ─── KEMEWORK: TASKS ───
  { resourceKey: "kemework_task", displayName: "Kemework Task", module: "kemework", resourceType: "entity", description: "Task posted by a customer", availableActions: ["view","create","edit","delete","submit","assign","approve","reject","bid","upload_media"], sortOrder: 38 },
  { resourceKey: "post_task_form", displayName: "Post Task Form", module: "kemework", resourceType: "form", route: "/kemework/post-task", description: "Form for customers to post a task", availableActions: ["view","create","submit","upload_media"], sortOrder: 39 },
  { resourceKey: "browse_tasks_page", displayName: "Browse Tasks Page", module: "kemework", resourceType: "page", route: "/kemework/tasks", description: "Public task browsing page", availableActions: ["view"], sortOrder: 40 },
  { resourceKey: "task_detail_page", displayName: "Task Detail Page", module: "kemework", resourceType: "page", route: "/kemework/task/:slug", description: "Individual task detail", availableActions: ["view","bid","message","assign"], sortOrder: 41 },
  { resourceKey: "task_bidding", displayName: "Submit Bid on Task", module: "kemework", resourceType: "feature", description: "Submit a bid/proposal on a task", availableActions: ["create","edit","delete"], sortOrder: 42 },
  { resourceKey: "task_assignment", displayName: "Assign Task to Professional", module: "kemework", resourceType: "feature", description: "Assign a task to a specific professional", availableActions: ["assign"], sortOrder: 43 },
  { resourceKey: "task_delivery", displayName: "Deliver Completed Task", module: "kemework", resourceType: "feature", description: "Mark task as delivered with proof", availableActions: ["submit","upload_media"], sortOrder: 44 },
  { resourceKey: "task_review_rating", displayName: "Task Review & Rating", module: "kemework", resourceType: "feature", description: "Leave a review/rating after task completion", availableActions: ["create"], sortOrder: 45 },

  // ─── KEMEWORK: SERVICES ───
  { resourceKey: "kemework_service", displayName: "Kemework Service Listing", module: "kemework", resourceType: "entity", description: "Service offered by a professional", availableActions: ["view","create","edit","delete","publish","approve","reject","upload_media"], sortOrder: 46 },
  { resourceKey: "add_service_form", displayName: "Add Service Form", module: "kemework", resourceType: "form", route: "/kemework/add-service", description: "Form to add a new service", availableActions: ["view","create","submit","upload_media"], sortOrder: 47 },
  { resourceKey: "browse_services_page", displayName: "Browse Services Page", module: "kemework", resourceType: "page", route: "/kemework/services", description: "Public service browsing page", availableActions: ["view"], sortOrder: 48 },
  { resourceKey: "service_detail_page", displayName: "Service Detail Page", module: "kemework", resourceType: "page", route: "/kemework/service/:slug", description: "Individual service detail", availableActions: ["view","purchase","message"], sortOrder: 49 },
  { resourceKey: "service_order", displayName: "Order a Service", module: "kemework", resourceType: "feature", description: "Place an order for a Kemework service", availableActions: ["create","edit","delete","purchase"], sortOrder: 50 },

  // ─── KEMEWORK: PROFESSIONALS ───
  { resourceKey: "professional_dashboard", displayName: "Professional Dashboard", module: "kemework", resourceType: "dashboard_section", description: "Dashboard for professionals", availableActions: ["access_dashboard"], sortOrder: 51 },
  { resourceKey: "professional_profile_page", displayName: "Professional Public Profile", module: "kemework", resourceType: "page", description: "Public-facing professional profile", availableActions: ["view","message"], sortOrder: 52 },
  { resourceKey: "pro_portfolio", displayName: "Professional Portfolio", module: "kemework", resourceType: "feature", description: "Portfolio of past work", availableActions: ["view","create","edit","delete","upload_media"], sortOrder: 53 },
  { resourceKey: "pro_accreditation", displayName: "Accreditation Program", module: "kemework", resourceType: "feature", description: "Apply for Kemedar accreditation", availableActions: ["view","create","submit"], sortOrder: 54 },
  { resourceKey: "pro_earnings", displayName: "Professional Earnings", module: "kemework", resourceType: "feature", description: "View and withdraw professional earnings", availableActions: ["view","withdraw"], sortOrder: 55 },
  { resourceKey: "find_professionals_page", displayName: "Find Professionals Page", module: "kemework", resourceType: "page", route: "/kemework/find-professionals", description: "Public professionals directory", availableActions: ["view"], sortOrder: 56 },
  { resourceKey: "preferred_program_page", displayName: "Preferred Professional Program Page", module: "kemework", resourceType: "page", description: "Accreditation program info page", availableActions: ["view","create"], sortOrder: 57 },

  // ─── KEMETRO: PRODUCTS ───
  { resourceKey: "kemetro_product", displayName: "Kemetro Product", module: "kemetro", resourceType: "entity", description: "Product on the Kemetro marketplace", availableActions: ["view","create","edit","delete","publish","approve","reject","upload_media","feature","import"], sortOrder: 58 },
  { resourceKey: "add_product_form", displayName: "Add Product Form", module: "kemetro", resourceType: "form", route: "/kemetro/seller/products/add", description: "Form to add a new product", availableActions: ["view","create","submit","upload_media"], sortOrder: 59 },
  { resourceKey: "kemetro_search_page", displayName: "Kemetro Search/Browse Page", module: "kemetro", resourceType: "page", route: "/kemetro/search", description: "Public product search", availableActions: ["view"], sortOrder: 60 },
  { resourceKey: "product_detail_page", displayName: "Product Detail Page", module: "kemetro", resourceType: "page", route: "/kemetro/product/:slug", description: "Individual product detail", availableActions: ["view","purchase","message"], sortOrder: 61 },
  { resourceKey: "kemetro_cart", displayName: "Shopping Cart", module: "kemetro", resourceType: "feature", description: "Shopping cart management", availableActions: ["view","create","edit","delete","purchase"], sortOrder: 62 },
  { resourceKey: "kemetro_checkout", displayName: "Checkout Flow", module: "kemetro", resourceType: "feature", description: "Order checkout process", availableActions: ["view","purchase"], sortOrder: 63 },
  { resourceKey: "product_rfq", displayName: "Request for Quotation (RFQ)", module: "kemetro", resourceType: "feature", description: "Request a quote from sellers", availableActions: ["view","create","edit","delete","submit","bid"], sortOrder: 64 },

  // ─── KEMETRO: SELLER ───
  { resourceKey: "seller_dashboard", displayName: "Seller Dashboard", module: "kemetro", resourceType: "dashboard_section", description: "Seller control panel", availableActions: ["access_dashboard"], sortOrder: 65 },
  { resourceKey: "seller_products_manage", displayName: "Seller — Products Management", module: "kemetro", resourceType: "feature", description: "Manage own products", availableActions: ["view","create","edit","delete","publish","bulk_action"], sortOrder: 66 },
  { resourceKey: "seller_orders_manage", displayName: "Seller — Orders Management", module: "kemetro", resourceType: "feature", description: "Manage incoming orders", availableActions: ["view","edit","approve","reject","bulk_action"], sortOrder: 67 },
  { resourceKey: "seller_shipments_manage", displayName: "Seller — Shipments", module: "kemetro", resourceType: "feature", description: "Create and manage shipments", availableActions: ["view","create","edit","manage"], sortOrder: 68 },
  { resourceKey: "seller_coupons", displayName: "Seller — Coupons", module: "kemetro", resourceType: "feature", description: "Create and manage discount coupons", availableActions: ["view","create","edit","delete"], sortOrder: 69 },
  { resourceKey: "seller_promotions", displayName: "Seller — Promotions & Campaigns", module: "kemetro", resourceType: "feature", description: "Create promotional campaigns", availableActions: ["view","create","edit","delete"], sortOrder: 70 },
  { resourceKey: "seller_earnings", displayName: "Seller — Earnings & Payouts", module: "kemetro", resourceType: "feature", description: "View earnings and request payouts", availableActions: ["view","withdraw"], sortOrder: 71 },
  { resourceKey: "seller_analytics", displayName: "Seller — Analytics", module: "kemetro", resourceType: "feature", description: "Store analytics and reports", availableActions: ["view","export"], sortOrder: 72 },
  { resourceKey: "seller_store_profile", displayName: "Seller — Store Profile", module: "kemetro", resourceType: "feature", description: "Edit store profile and branding", availableActions: ["view","edit","upload_media"], sortOrder: 73 },

  // ─── KEMETRO: SHIPPER ───
  { resourceKey: "shipper_dashboard", displayName: "Shipper Dashboard", module: "kemetro", resourceType: "dashboard_section", description: "Shipper control panel", availableActions: ["access_dashboard"], sortOrder: 74 },
  { resourceKey: "shipper_requests", displayName: "Shipper — Available Requests", module: "kemetro", resourceType: "feature", description: "Browse available shipment requests", availableActions: ["view","bid"], sortOrder: 75 },
  { resourceKey: "shipper_active", displayName: "Shipper — Active Deliveries", module: "kemetro", resourceType: "feature", description: "Manage active delivery jobs", availableActions: ["view","edit","submit","upload_media"], sortOrder: 76 },
  { resourceKey: "shipper_earnings", displayName: "Shipper — Earnings", module: "kemetro", resourceType: "feature", description: "View and withdraw shipper earnings", availableActions: ["view","withdraw"], sortOrder: 77 },

  // ─── SHARED: DASHBOARD & ACCOUNT ───
  { resourceKey: "main_dashboard", displayName: "Main Dashboard", module: "shared", resourceType: "dashboard_section", description: "Primary user dashboard", availableActions: ["access_dashboard"], sortOrder: 78 },
  { resourceKey: "dashboard_messages", displayName: "Dashboard — Messages", module: "shared", resourceType: "feature", description: "Messaging system", availableActions: ["view","create","delete"], sortOrder: 79 },
  { resourceKey: "dashboard_notifications", displayName: "Dashboard — Notifications", module: "shared", resourceType: "feature", description: "Notification center", availableActions: ["view","delete"], sortOrder: 80 },
  { resourceKey: "dashboard_profile", displayName: "Dashboard — My Profile", module: "shared", resourceType: "feature", description: "Personal profile management", availableActions: ["view","edit","upload_media"], sortOrder: 81 },
  { resourceKey: "dashboard_wallet", displayName: "Dashboard — Wallet", module: "shared", resourceType: "feature", description: "Wallet and balance", availableActions: ["view","withdraw","purchase"], sortOrder: 82 },
  { resourceKey: "dashboard_invoices", displayName: "Dashboard — Invoices", module: "shared", resourceType: "feature", description: "Invoice history", availableActions: ["view","export"], sortOrder: 83 },
  { resourceKey: "dashboard_subscription", displayName: "Dashboard — Subscription", module: "shared", resourceType: "feature", description: "Subscription plan management", availableActions: ["view","purchase"], sortOrder: 84 },
  { resourceKey: "dashboard_support", displayName: "Dashboard — Support Tickets", module: "shared", resourceType: "feature", description: "Customer support tickets", availableActions: ["view","create","edit"], sortOrder: 85 },
  { resourceKey: "dashboard_payment_methods", displayName: "Dashboard — Payment Methods", module: "shared", resourceType: "feature", description: "Saved payment methods", availableActions: ["view","create","edit","delete"], sortOrder: 86 },
  { resourceKey: "premium_services_hub", displayName: "Buy / Premium Services Hub", module: "shared", resourceType: "page", route: "/buy", description: "Paid services and upgrades page", availableActions: ["view","purchase"], sortOrder: 87 },
  { resourceKey: "user_benefits_pages", displayName: "User Benefits Pages", module: "shared", resourceType: "page", description: "Marketing pages for role benefits", availableActions: ["view"], sortOrder: 88 },
  { resourceKey: "user_settings", displayName: "User Settings", module: "shared", resourceType: "feature", description: "App settings and preferences", availableActions: ["view","edit"], sortOrder: 89 },
  { resourceKey: "module_toggle_settings", displayName: "Module Toggle in Settings", module: "shared", resourceType: "feature", description: "Enable/disable modules in settings", availableActions: ["view","edit"], sortOrder: 90 },
  { resourceKey: "public_homepage", displayName: "Kemedar Homepage", module: "shared", resourceType: "page", route: "/", description: "Main public homepage", availableActions: ["view"], sortOrder: 91 },
  { resourceKey: "registration_page", displayName: "Registration Page", module: "shared", resourceType: "page", route: "/auth/register", description: "Account registration page", availableActions: ["view","create"], sortOrder: 92 },
  { resourceKey: "login_page", displayName: "Login Page", module: "shared", resourceType: "page", route: "/auth/login", description: "Login page", availableActions: ["view"], sortOrder: 93 },

  // ─── ADMIN ───
  { resourceKey: "admin_panel_access", displayName: "Admin Panel Access", module: "admin", resourceType: "feature", description: "Access to the admin panel", availableActions: ["access_dashboard"], sortOrder: 94 },
  { resourceKey: "admin_users_management", displayName: "Admin — Users Management", module: "admin", resourceType: "feature", description: "Manage all platform users", availableActions: ["view","edit","delete","verify","approve","reject","export","bulk_action"], sortOrder: 95 },
  { resourceKey: "admin_properties_management", displayName: "Admin — Properties Management", module: "admin", resourceType: "feature", description: "Manage all property listings", availableActions: ["view","edit","delete","approve","reject","verify","feature","export","import","bulk_action"], sortOrder: 96 },
  { resourceKey: "admin_import_scraping", displayName: "Admin — Import & Scraping", module: "admin", resourceType: "feature", description: "Data import and web scraping tools", availableActions: ["view","create","manage","import","export"], sortOrder: 97 },
  { resourceKey: "admin_crm", displayName: "Admin — CRM", module: "admin", resourceType: "feature", description: "Platform-wide CRM", availableActions: ["view","create","edit","delete","export","assign","bulk_action"], sortOrder: 98 },
  { resourceKey: "admin_notifications_send", displayName: "Admin — Send Notifications", module: "admin", resourceType: "feature", description: "Send platform notifications", availableActions: ["view","create","submit","delete"], sortOrder: 99 },
  { resourceKey: "admin_reports", displayName: "Admin — Reports", module: "admin", resourceType: "feature", description: "Platform analytics and reports", availableActions: ["view","export"], sortOrder: 100 },
  { resourceKey: "admin_settings", displayName: "Admin — System Settings", module: "admin", resourceType: "feature", description: "System-wide settings", availableActions: ["view","edit","manage"], sortOrder: 101 },
  { resourceKey: "admin_module_control", displayName: "Admin — Module Control Center", module: "admin", resourceType: "feature", description: "Enable/disable platform modules", availableActions: ["view","edit","manage"], sortOrder: 102 },
  { resourceKey: "admin_permissions_management", displayName: "Admin — Permissions Management", module: "admin", resourceType: "feature", description: "Manage RBAC roles and permissions", availableActions: ["view","edit","manage"], sortOrder: 103 },
];

// ─── DEFAULT ROLE PERMISSIONS ─────────────────────────────────────────────────
// Format: [roleKey, resourceKey, actionKey, permissionLevel, guestBehavior?, conditions?]
export const DEFAULT_PERMISSIONS = [
  // ── GUEST ──
  ["guest","property_listing","view","allow",null,null],
  ["guest","property_listing","create","deny","redirect_login",null],
  ["guest","property_listing","message","deny","redirect_login",null],
  ["guest","add_property_form","view","allow",null,null],
  ["guest","add_property_form","create","allow",null,null],
  ["guest","add_property_form","submit","deny","allow_form_fill",null],
  ["guest","add_property_form","upload_media","deny","allow_form_fill",null],
  ["guest","property_search","view","allow",null,null],
  ["guest","property_detail_page","view","allow",null,null],
  ["guest","property_detail_page","message","deny","show_teaser",null],
  ["guest","buy_request","view","allow",null,null],
  ["guest","buy_request","create","deny","redirect_login",null],
  ["guest","buy_request","submit","deny","allow_form_fill",null],
  ["guest","add_buy_request_form","view","allow",null,null],
  ["guest","add_buy_request_form","submit","deny","allow_form_fill",null],
  ["guest","add_project_form","view","allow",null,null],
  ["guest","add_project_form","submit","deny","allow_form_fill",null],
  ["guest","post_task_form","view","allow",null,null],
  ["guest","post_task_form","create","allow",null,null],
  ["guest","post_task_form","submit","deny","allow_form_fill",null],
  ["guest","add_service_form","view","allow",null,null],
  ["guest","add_service_form","submit","deny","allow_form_fill",null],
  ["guest","browse_tasks_page","view","allow",null,null],
  ["guest","task_bidding","create","deny","redirect_login",null],
  ["guest","service_detail_page","view","allow",null,null],
  ["guest","service_detail_page","purchase","deny","show_teaser",null],
  ["guest","kemetro_search_page","view","allow",null,null],
  ["guest","product_detail_page","view","allow",null,null],
  ["guest","product_detail_page","purchase","deny","show_teaser",null],
  ["guest","kemetro_cart","view","allow",null,null],
  ["guest","kemetro_cart","purchase","deny","redirect_login",null],
  ["guest","user_benefits_pages","view","allow",null,null],
  ["guest","property_valuation_tool","view","allow",null,null],
  ["guest","property_valuation_tool","create","deny","show_teaser",null],
  ["guest","main_dashboard","access_dashboard","deny","redirect_login",null],
  ["guest","premium_services_hub","view","allow",null,null],
  ["guest","premium_services_hub","purchase","deny","redirect_login",null],
  ["guest","registration_page","view","allow",null,null],
  ["guest","registration_page","create","allow",null,null],
  ["guest","login_page","view","allow",null,null],
  ["guest","public_homepage","view","allow",null,null],
  ["guest","project_search","view","allow",null,null],
  ["guest","browse_services_page","view","allow",null,null],
  ["guest","find_agents_page","view","allow",null,null],
  ["guest","find_agencies_page","view","allow",null,null],
  ["guest","find_developers_page","view","allow",null,null],
  ["guest","find_franchise_page","view","allow",null,null],
  ["guest","agent_profile_page","view","allow",null,null],
  ["guest","professional_profile_page","view","allow",null,null],
  ["guest","find_professionals_page","view","allow",null,null],
  ["guest","preferred_program_page","view","allow",null,null],
  ["guest","admin_panel_access","access_dashboard","deny","full_block",null],
  ["guest","admin_users_management","view","deny","full_block",null],
  ["guest","admin_properties_management","view","deny","full_block",null],

  // ── COMMON USER ──
  ["common_user","main_dashboard","access_dashboard","allow",null,null],
  ["common_user","dashboard_messages","view","allow",null,null],
  ["common_user","dashboard_messages","create","allow",null,null],
  ["common_user","dashboard_notifications","view","allow",null,null],
  ["common_user","dashboard_profile","view","allow",null,null],
  ["common_user","dashboard_profile","edit","allow",null,null],
  ["common_user","dashboard_profile","upload_media","allow",null,null],
  ["common_user","dashboard_wallet","view","allow",null,null],
  ["common_user","dashboard_invoices","view","allow",null,null],
  ["common_user","dashboard_subscription","view","allow",null,null],
  ["common_user","dashboard_subscription","purchase","allow",null,null],
  ["common_user","dashboard_support","view","allow",null,null],
  ["common_user","dashboard_support","create","allow",null,null],
  ["common_user","dashboard_payment_methods","view","allow",null,null],
  ["common_user","dashboard_payment_methods","create","allow",null,null],
  ["common_user","dashboard_payment_methods","edit","allow",null,null],
  ["common_user","property_listing","view","allow",null,null],
  ["common_user","property_listing","create","allow_own_only",null,{maxCount:3}],
  ["common_user","property_listing","edit","allow_own_only",null,{ownResourceOnly:true}],
  ["common_user","property_listing","delete","allow_own_only",null,{ownResourceOnly:true}],
  ["common_user","add_property_form","view","allow",null,null],
  ["common_user","add_property_form","create","allow",null,null],
  ["common_user","add_property_form","submit","allow",null,null],
  ["common_user","add_property_form","upload_media","allow",null,null],
  ["common_user","property_favorites","view","allow",null,null],
  ["common_user","property_favorites","create","allow",null,null],
  ["common_user","property_favorites","delete","allow",null,null],
  ["common_user","property_compare","view","allow",null,null],
  ["common_user","buyer_organizer","view","allow",null,null],
  ["common_user","buyer_organizer","create","allow",null,null],
  ["common_user","buyer_organizer","edit","allow",null,null],
  ["common_user","buyer_organizer","delete","allow",null,null],
  ["common_user","seller_organizer","view","allow",null,null],
  ["common_user","seller_organizer","create","allow",null,null],
  ["common_user","seller_organizer","edit","allow",null,null],
  ["common_user","buy_request","view","allow",null,null],
  ["common_user","buy_request","create","allow_own_only",null,null],
  ["common_user","buy_request","edit","allow_own_only",null,{ownResourceOnly:true}],
  ["common_user","buy_request","delete","allow_own_only",null,{ownResourceOnly:true}],
  ["common_user","buy_request","submit","allow_own_only",null,null],
  ["common_user","property_valuation_tool","view","allow",null,null],
  ["common_user","property_valuation_tool","create","allow",null,null],
  ["common_user","property_ai_pricing","view","allow",null,null],
  ["common_user","property_ai_description","view","allow",null,null],
  ["common_user","module_toggle_settings","view","allow",null,null],
  ["common_user","module_toggle_settings","edit","allow",null,null],
  ["common_user","user_settings","view","allow",null,null],
  ["common_user","user_settings","edit","allow",null,null],
  ["common_user","kemetro_cart","view","allow",null,null],
  ["common_user","kemetro_cart","create","allow",null,null],
  ["common_user","kemetro_cart","edit","allow",null,null],
  ["common_user","kemetro_cart","delete","allow",null,null],
  ["common_user","kemetro_checkout","view","allow",null,null],
  ["common_user","kemetro_checkout","purchase","allow",null,null],
  ["common_user","product_rfq","view","allow",null,null],
  ["common_user","product_rfq","create","allow",null,null],
  ["common_user","product_rfq","submit","allow",null,null],
  ["common_user","post_task_form","view","allow",null,null],
  ["common_user","post_task_form","create","allow",null,null],
  ["common_user","post_task_form","submit","allow",null,null],
  ["common_user","browse_tasks_page","view","allow",null,null],
  ["common_user","task_assignment","assign","allow_own_only",null,null],
  ["common_user","task_review_rating","create","allow",null,null],

  // ── AGENT ──
  ["agent","property_listing","create","allow",null,{maxCount:30,requiresSubscription:"starter"}],
  ["agent","property_listing","edit","allow_own_only",null,{ownResourceOnly:true}],
  ["agent","property_listing","delete","allow_own_only",null,{ownResourceOnly:true}],
  ["agent","property_listing","publish","allow_own_only",null,{ownResourceOnly:true}],
  ["agent","add_property_form","view","allow",null,null],
  ["agent","add_property_form","create","allow",null,null],
  ["agent","add_property_form","submit","allow",null,null],
  ["agent","add_property_form","upload_media","allow",null,null],
  ["agent","agent_dashboard","access_dashboard","allow",null,null],
  ["agent","agent_clients_crm","view","allow",null,null],
  ["agent","agent_clients_crm","create","allow",null,null],
  ["agent","agent_clients_crm","edit","allow",null,null],
  ["agent","agent_clients_crm","delete","allow",null,null],
  ["agent","agent_appointments","view","allow",null,null],
  ["agent","agent_appointments","create","allow",null,null],
  ["agent","agent_appointments","edit","allow",null,null],
  ["agent","agent_appointments","delete","allow",null,null],
  ["agent","agent_analytics","view","allow",null,null],
  ["agent","agent_analytics","export","allow",null,null],
  ["agent","project_listing","view","allow",null,null],
  ["agent","project_listing","create","allow",null,{maxCount:1}],

  // ── DEVELOPER ──
  ["developer","project_listing","view","allow",null,null],
  ["developer","project_listing","create","allow",null,null],
  ["developer","project_listing","edit","allow_own_only",null,null],
  ["developer","project_listing","delete","allow_own_only",null,null],
  ["developer","project_listing","publish","allow_own_only",null,null],
  ["developer","project_listing","upload_media","allow",null,null],
  ["developer","project_units","view","allow",null,null],
  ["developer","project_units","create","allow",null,null],
  ["developer","project_units","edit","allow",null,null],
  ["developer","project_units","delete","allow",null,null],
  ["developer","developer_projects","view","allow",null,null],
  ["developer","developer_projects","create","allow",null,null],
  ["developer","developer_projects","edit","allow",null,null],
  ["developer","developer_leads","view","allow",null,null],
  ["developer","developer_leads","create","allow",null,null],
  ["developer","developer_leads","edit","allow",null,null],
  ["developer","property_listing","create","allow",null,null],

  // ── FRANCHISE OWNER AREA ──
  ["franchise_owner_area","franchise_area_users","view","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_users","verify","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_users","message","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_properties","view","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_properties","verify","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_properties","approve","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_properties","reject","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_properties","feature","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_projects","view","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_projects","verify","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_projects","approve","allow_area_only",null,null],
  ["franchise_owner_area","franchise_area_projects","reject","allow_area_only",null,null],
  ["franchise_owner_area","franchise_verify_user","verify","allow",null,null],
  ["franchise_owner_area","franchise_verify_user","reject","allow",null,null],
  ["franchise_owner_area","franchise_accredit_handyman","accredit","allow",null,null],
  ["franchise_owner_area","franchise_accredit_handyman","reject","allow",null,null],
  ["franchise_owner_area","franchise_kemetro_sellers","view","allow_area_only",null,null],
  ["franchise_owner_area","franchise_kemetro_sellers","verify","allow_area_only",null,null],
  ["franchise_owner_area","franchise_business_manager","view","allow",null,null],
  ["franchise_owner_area","franchise_business_manager","create","allow",null,null],
  ["franchise_owner_area","franchise_business_manager","edit","allow",null,null],
  ["franchise_owner_area","franchise_business_manager","delete","allow",null,null],
  ["franchise_owner_area","franchise_business_manager","manage","allow",null,null],
  ["franchise_owner_area","franchise_bulk_comms","view","allow",null,null],
  ["franchise_owner_area","franchise_bulk_comms","create","allow",null,null],
  ["franchise_owner_area","franchise_bulk_comms","submit","allow",null,null],

  // ── PROFESSIONAL ──
  ["professional","professional_dashboard","access_dashboard","allow",null,null],
  ["professional","add_service_form","view","allow",null,null],
  ["professional","add_service_form","create","allow",null,{requiresSubscription:"starter"}],
  ["professional","add_service_form","submit","allow",null,{requiresSubscription:"starter"}],
  ["professional","kemework_service","view","allow",null,null],
  ["professional","kemework_service","create","allow_own_only",null,null],
  ["professional","kemework_service","edit","allow_own_only",null,{ownResourceOnly:true}],
  ["professional","kemework_service","delete","allow_own_only",null,{ownResourceOnly:true}],
  ["professional","kemework_service","publish","allow_own_only",null,{ownResourceOnly:true}],
  ["professional","pro_portfolio","view","allow",null,null],
  ["professional","pro_portfolio","create","allow",null,null],
  ["professional","pro_portfolio","edit","allow",null,null],
  ["professional","pro_portfolio","delete","allow",null,null],
  ["professional","pro_portfolio","upload_media","allow",null,null],
  ["professional","pro_accreditation","view","allow",null,null],
  ["professional","pro_accreditation","create","allow",null,null],
  ["professional","pro_accreditation","submit","allow",null,null],
  ["professional","pro_earnings","view","allow",null,null],
  ["professional","pro_earnings","withdraw","allow",null,null],
  ["professional","task_bidding","create","allow",null,null],
  ["professional","task_bidding","edit","allow",null,null],
  ["professional","task_bidding","delete","allow",null,null],
  ["professional","task_delivery","submit","allow",null,null],
  ["professional","task_delivery","upload_media","allow",null,null],

  // ── PRODUCT SELLER ──
  ["product_seller","seller_dashboard","access_dashboard","allow",null,null],
  ["product_seller","add_product_form","view","allow",null,null],
  ["product_seller","add_product_form","create","allow",null,null],
  ["product_seller","add_product_form","submit","allow",null,null],
  ["product_seller","add_product_form","upload_media","allow",null,null],
  ["product_seller","seller_products_manage","view","allow_own_only",null,null],
  ["product_seller","seller_products_manage","create","allow_own_only",null,null],
  ["product_seller","seller_products_manage","edit","allow_own_only",null,null],
  ["product_seller","seller_products_manage","delete","allow_own_only",null,null],
  ["product_seller","seller_products_manage","publish","allow_own_only",null,null],
  ["product_seller","seller_orders_manage","view","allow_own_only",null,null],
  ["product_seller","seller_orders_manage","edit","allow_own_only",null,null],
  ["product_seller","seller_shipments_manage","view","allow",null,null],
  ["product_seller","seller_shipments_manage","create","allow",null,null],
  ["product_seller","seller_coupons","view","allow_own_only",null,null],
  ["product_seller","seller_coupons","create","allow_own_only",null,null],
  ["product_seller","seller_coupons","edit","allow_own_only",null,null],
  ["product_seller","seller_coupons","delete","allow_own_only",null,null],
  ["product_seller","seller_promotions","view","allow_own_only",null,null],
  ["product_seller","seller_promotions","create","allow_own_only",null,null],
  ["product_seller","seller_promotions","edit","allow_own_only",null,null],
  ["product_seller","seller_promotions","delete","allow_own_only",null,null],
  ["product_seller","seller_earnings","view","allow",null,null],
  ["product_seller","seller_earnings","withdraw","allow",null,null],
  ["product_seller","seller_analytics","view","allow",null,null],
  ["product_seller","seller_analytics","export","allow",null,null],
  ["product_seller","seller_store_profile","view","allow",null,null],
  ["product_seller","seller_store_profile","edit","allow",null,null],
  ["product_seller","seller_store_profile","upload_media","allow",null,null],

  // ── SHIPPER ──
  ["shipper","shipper_dashboard","access_dashboard","allow",null,null],
  ["shipper","shipper_requests","view","allow",null,null],
  ["shipper","shipper_requests","bid","allow",null,null],
  ["shipper","shipper_active","view","allow",null,null],
  ["shipper","shipper_active","edit","allow",null,null],
  ["shipper","shipper_active","submit","allow",null,null],
  ["shipper","shipper_active","upload_media","allow",null,null],
  ["shipper","shipper_earnings","view","allow",null,null],
  ["shipper","shipper_earnings","withdraw","allow",null,null],

  // ── ADMIN ──
  ["admin","admin_panel_access","access_dashboard","allow",null,null],
  ["admin","admin_users_management","view","allow",null,null],
  ["admin","admin_users_management","edit","allow",null,null],
  ["admin","admin_users_management","delete","allow",null,null],
  ["admin","admin_users_management","verify","allow",null,null],
  ["admin","admin_users_management","approve","allow",null,null],
  ["admin","admin_users_management","reject","allow",null,null],
  ["admin","admin_users_management","export","allow",null,null],
  ["admin","admin_users_management","bulk_action","allow",null,null],
  ["admin","admin_properties_management","view","allow",null,null],
  ["admin","admin_properties_management","edit","allow",null,null],
  ["admin","admin_properties_management","delete","allow",null,null],
  ["admin","admin_properties_management","approve","allow",null,null],
  ["admin","admin_properties_management","reject","allow",null,null],
  ["admin","admin_properties_management","verify","allow",null,null],
  ["admin","admin_properties_management","feature","allow",null,null],
  ["admin","admin_properties_management","export","allow",null,null],
  ["admin","admin_properties_management","import","allow",null,null],
  ["admin","admin_properties_management","bulk_action","allow",null,null],
  ["admin","admin_import_scraping","view","allow",null,null],
  ["admin","admin_import_scraping","create","allow",null,null],
  ["admin","admin_import_scraping","manage","allow",null,null],
  ["admin","admin_import_scraping","import","allow",null,null],
  ["admin","admin_import_scraping","export","allow",null,null],
  ["admin","admin_crm","view","allow",null,null],
  ["admin","admin_crm","create","allow",null,null],
  ["admin","admin_crm","edit","allow",null,null],
  ["admin","admin_crm","delete","allow",null,null],
  ["admin","admin_crm","export","allow",null,null],
  ["admin","admin_crm","assign","allow",null,null],
  ["admin","admin_crm","bulk_action","allow",null,null],
  ["admin","admin_notifications_send","view","allow",null,null],
  ["admin","admin_notifications_send","create","allow",null,null],
  ["admin","admin_notifications_send","submit","allow",null,null],
  ["admin","admin_notifications_send","delete","allow",null,null],
  ["admin","admin_reports","view","allow",null,null],
  ["admin","admin_reports","export","allow",null,null],
  ["admin","admin_settings","view","allow",null,null],
  ["admin","admin_settings","edit","allow",null,null],
  ["admin","admin_settings","manage","allow",null,null],
  ["admin","admin_module_control","view","allow",null,null],
  ["admin","admin_module_control","edit","allow",null,null],
  ["admin","admin_module_control","manage","allow",null,null],
  ["admin","admin_permissions_management","view","allow",null,null],
  ["admin","admin_permissions_management","edit","allow",null,null],
  ["admin","admin_permissions_management","manage","allow",null,null],
  ["admin","property_listing","view","allow",null,null],
  ["admin","property_listing","approve","allow",null,null],
  ["admin","property_listing","reject","allow",null,null],
  ["admin","property_listing","verify","allow",null,null],
  ["admin","property_listing","feature","allow",null,null],
  ["admin","property_listing","delete","allow",null,null],
  ["admin","project_listing","view","allow",null,null],
  ["admin","project_listing","approve","allow",null,null],
  ["admin","project_listing","reject","allow",null,null],
  ["admin","project_listing","verify","allow",null,null],
  ["admin","project_listing","feature","allow",null,null],
  ["admin","kemetro_product","view","allow",null,null],
  ["admin","kemetro_product","approve","allow",null,null],
  ["admin","kemetro_product","reject","allow",null,null],
  ["admin","kemetro_product","feature","allow",null,null],
  ["admin","kemetro_product","delete","allow",null,null],
  ["admin","kemework_service","view","allow",null,null],
  ["admin","kemework_service","approve","allow",null,null],
  ["admin","kemework_service","reject","allow",null,null],
  ["admin","kemework_service","delete","allow",null,null],
  ["admin","kemework_task","view","allow",null,null],
  ["admin","kemework_task","assign","allow",null,null],
  ["admin","kemework_task","delete","allow",null,null],

  // ── SUPER ADMIN (all admin plus extra) ──
  ["super_admin","admin_panel_access","access_dashboard","allow",null,null],
  ["super_admin","admin_permissions_management","manage","allow",null,null],
  ["super_admin","admin_settings","manage","allow",null,null],
  ["super_admin","admin_module_control","manage","allow",null,null],
];