import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { TrendingUp, Package, Zap } from "lucide-react";

export default function CommunityWeeklyDigest({ community, posts, items, events }) {
  const [digest, setDigest] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [compoundDeals, setCompoundDeals] = useState([]);
  const [signals, setSignals] = useState([]);

  useEffect(() => {
    if (community?.id) {
      base44.entities.CompoundDeal.filter({ compoundName: community.compoundName || community.communityName }).then(setCompoundDeals).catch(() => {});
      base44.entities.DemandSignal.filter({ status: "detected" }).then(s => setSignals(s.slice(0, 3))).catch(() => {});
    }
  }, [community]);

  const generateDigest = async () => {
    setGenerating(true);
    const topPosts = posts.slice(0, 8).map(p => `[${p.postType}] ${p.title || p.content?.slice(0, 100)}`).join("\n");
    const result = await base44.integrations.Core.InvokeLLM({
      prompt: `You are an AI assistant for Kemedar Community™, writing a friendly weekly digest for residents of ${community?.communityName}.

Community data this week:
- ${posts.length} total posts
- ${items.length} marketplace items
- ${events.length} events
- Top posts:
${topPosts}

Write a warm, concise weekly digest with:
1. A friendly greeting (2 sentences max)
2. "Top Discussions" — 3 bullet points from the most interesting posts
3. "Marketplace Highlights" — 1-2 sentences about items for sale/free
4. "AI Insights" — 2 bullet points: detected Kemework opportunities, price signals, or group buy opportunities
5. "Coming Up" — mention any events

Keep it conversational, under 250 words, use emojis. End with a warm closing.`,
      response_json_schema: {
        type: "object",
        properties: {
          greeting: { type: "string" },
          topDiscussions: { type: "array", items: { type: "string" } },
          marketplaceHighlight: { type: "string" },
          aiInsights: { type: "array", items: { type: "string" } },
          comingUp: { type: "string" },
          closing: { type: "string" },
        }
      }
    });
    setDigest(result);
    setGenerating(false);
  };

  // Stats for the week
  const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const thisWeekPosts = posts.filter(p => new Date(p.created_date) > weekAgo);
  const kemeworkLeads = posts.filter(p => p.suggestedKemeworkCategory && new Date(p.created_date) > weekAgo).length;
  const marketplaceSales = items.filter(i => new Date(i.created_date) > weekAgo).length;
  const activeDeals = compoundDeals.filter(d => d.status === "forming" || d.status === "threshold_reached");

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="bg-gradient-to-br from-violet-600 to-purple-700 rounded-2xl p-5 text-white">
        <p className="text-2xl font-black mb-0.5">📋 Weekly Digest</p>
        <p className="text-violet-200 text-sm">
          Week of {new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toLocaleDateString("en-EG", { month: "short", day: "numeric" })} — {new Date().toLocaleDateString("en-EG", { month: "short", day: "numeric" })}
        </p>
      </div>

      {/* Weekly stats */}
      <div className="grid grid-cols-2 gap-3">
        {[
          { icon: "💬", val: thisWeekPosts.length, label: "Posts this week", color: "text-orange-600", bg: "bg-orange-50" },
          { icon: "🔧", val: kemeworkLeads, label: "Service leads detected", color: "text-emerald-600", bg: "bg-emerald-50" },
          { icon: "🛍", val: marketplaceSales, label: "New marketplace items", color: "text-teal-600", bg: "bg-teal-50" },
          { icon: "👥", val: community?.activeMembers || community?.totalMembers || 0, label: "Active members", color: "text-blue-600", bg: "bg-blue-50" },
        ].map(s => (
          <div key={s.label} className={`${s.bg} rounded-2xl p-4 border border-white shadow-sm`}>
            <span className="text-2xl">{s.icon}</span>
            <p className={`text-2xl font-black mt-1 ${s.color}`}>{s.val}</p>
            <p className="text-[11px] text-gray-500 font-semibold">{s.label}</p>
          </div>
        ))}
      </div>

      {/* AI Digest */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between">
          <div>
            <p className="font-black text-gray-900">🤖 AI Weekly Summary</p>
            <p className="text-xs text-gray-400">Generated by Kemedar AI</p>
          </div>
          <button
            onClick={generateDigest}
            disabled={generating}
            className="text-xs bg-violet-500 text-white font-bold px-3 py-1.5 rounded-xl hover:bg-violet-600 disabled:opacity-60 transition-colors flex items-center gap-1"
          >
            {generating ? <><span className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin" /> Generating...</> : "✨ Generate"}
          </button>
        </div>

        {digest ? (
          <div className="px-5 py-4 space-y-4">
            <p className="text-sm text-gray-700 leading-relaxed">{digest.greeting}</p>

            {digest.topDiscussions?.length > 0 && (
              <div>
                <p className="font-black text-gray-900 text-xs uppercase tracking-wide mb-2">💬 Top Discussions</p>
                <ul className="space-y-1.5">
                  {digest.topDiscussions.map((d, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                      <span className="text-orange-500 font-black mt-0.5">•</span> {d}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {digest.marketplaceHighlight && (
              <div>
                <p className="font-black text-gray-900 text-xs uppercase tracking-wide mb-1">🛍 Marketplace</p>
                <p className="text-sm text-gray-700">{digest.marketplaceHighlight}</p>
              </div>
            )}

            {digest.aiInsights?.length > 0 && (
              <div className="bg-violet-50 rounded-xl p-3 border border-violet-100">
                <p className="font-black text-violet-800 text-xs uppercase tracking-wide mb-2">🧠 AI Insights</p>
                <ul className="space-y-1.5">
                  {digest.aiInsights.map((insight, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-violet-700">
                      <span className="font-black mt-0.5">→</span> {insight}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {digest.comingUp && (
              <div>
                <p className="font-black text-gray-900 text-xs uppercase tracking-wide mb-1">📅 Coming Up</p>
                <p className="text-sm text-gray-700">{digest.comingUp}</p>
              </div>
            )}

            {digest.closing && <p className="text-sm text-gray-600 italic border-t border-gray-100 pt-3">{digest.closing}</p>}
          </div>
        ) : (
          <div className="px-5 py-8 text-center text-gray-400">
            <p className="text-4xl mb-2">✨</p>
            <p className="font-bold text-sm">Generate your weekly AI digest</p>
            <p className="text-xs mt-1">AI summarizes top posts, marketplace activity, and community insights</p>
          </div>
        )}
      </div>

      {/* Group Buy Status */}
      {activeDeals.length > 0 && (
        <div>
          <p className="font-black text-gray-900 text-sm mb-2">🛒 Group Buy Status</p>
          <div className="space-y-2">
            {activeDeals.map(deal => {
              const progress = Math.min(100, Math.round((deal.currentParticipants || 0) / (deal.minParticipants || 1) * 100));
              return (
                <div key={deal.id} className="bg-white rounded-2xl border border-blue-100 shadow-sm p-4">
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-black text-gray-900 text-sm">{deal.productName || deal.dealTitle}</p>
                    <span className={`text-[10px] font-black px-2 py-0.5 rounded-full ${deal.status === "threshold_reached" ? "bg-green-100 text-green-700" : "bg-blue-100 text-blue-700"}`}>
                      {deal.status === "threshold_reached" ? "✅ REACHED" : "🔄 FORMING"}
                    </span>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
                      <div className="h-full bg-blue-500 rounded-full transition-all" style={{ width: `${progress}%` }} />
                    </div>
                    <span className="text-xs font-black text-blue-600 flex-shrink-0">{deal.currentParticipants || 0}/{deal.minParticipants}</span>
                  </div>
                  {deal.retailPricePerUnit && deal.targetPricePerUnit && (
                    <p className="text-xs text-gray-500 mt-1.5">
                      Save {Math.round((1 - deal.targetPricePerUnit / deal.retailPricePerUnit) * 100)}% vs retail
                      · {deal.targetPricePerUnit} EGP/m² target
                    </p>
                  )}
                  <Link to={`/kemetro/flash/compound/${deal.id}`} className="block text-center text-xs text-blue-600 font-bold mt-2 hover:underline">
                    Join this group buy →
                  </Link>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Market Intelligence */}
      {signals.length > 0 && (
        <div>
          <p className="font-black text-gray-900 text-sm mb-2">📈 Market Intelligence Update</p>
          <div className="space-y-2">
            {signals.map(s => (
              <div key={s.id} className="bg-purple-50 rounded-2xl border border-purple-100 p-4 flex items-start gap-3">
                <TrendingUp size={18} className="text-purple-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-bold text-purple-900 text-sm">{s.productCategory?.replace(/_/g, " ")} demand detected</p>
                  <p className="text-xs text-purple-600">~{s.estimatedBuyerCount} buyers · {s.estimatedDemandQty} m² · {Math.round((s.confidenceScore || 75))}% confidence</p>
                  {s.estimatedSavingsIfGrouped > 0 && (
                    <p className="text-xs font-bold text-green-600 mt-0.5">
                      Potential savings: {s.estimatedSavingsIfGrouped?.toLocaleString()} EGP if grouped
                    </p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Kemework recommendations */}
      <div className="bg-emerald-50 rounded-2xl border border-emerald-100 p-4">
        <p className="font-black text-emerald-800 text-sm mb-2">🔧 Kemework Recommendations This Week</p>
        {kemeworkLeads > 0 ? (
          <div className="space-y-1.5">
            <p className="text-sm text-emerald-700">
              🤖 AI detected <strong>{kemeworkLeads}</strong> service requests from community posts this week.
            </p>
            <p className="text-xs text-emerald-600">Categories: plumbing, electrical, AC maintenance, painting and more</p>
            <Link to="/kemework/find-professionals" className="block mt-2 text-center text-xs bg-emerald-500 text-white font-bold py-2 rounded-xl hover:bg-emerald-600 transition-colors">
              Browse Accredited Professionals →
            </Link>
          </div>
        ) : (
          <p className="text-sm text-emerald-700">No service requests detected this week. Post a help request to get instant professional recommendations.</p>
        )}
      </div>
    </div>
  );
}